<?php

namespace AppBundle\Repository;

/**
 * BranchesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchesRepository extends \Doctrine\ORM\EntityRepository
{
}
