<?php

namespace AppBundle\Repository;

/**
 * PeoplesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeoplesRepository extends \Doctrine\ORM\EntityRepository
{
}
