<?php

namespace AppBundle\Repository;

/**
 * VisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisionRepository extends \Doctrine\ORM\EntityRepository
{
}
