<?php

namespace AppBundle\Repository;

/**
 * WhoweareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhoweareRepository extends \Doctrine\ORM\EntityRepository
{
}
