branches_index:
    path:     /branches/
    defaults: { _controller: "AppBundle:Branches:index" }
    methods:  GET

branches_show:
    path:     /branches/{id}/show
    defaults: { _controller: "AppBundle:Branches:show" }
    methods:  GET

branches_new:
    path:     /admin/branches/new
    defaults: { _controller: "AppBundle:Branches:new" }
    methods:  [GET, POST]

branches_edit:
    path:     /admin/branches/{id}/edit
    defaults: { _controller: "AppBundle:Branches:edit" }
    methods:  [GET, POST]

branches_delete:
    path:     /admin/branches/{id}/delete
    defaults: { _controller: "AppBundle:Branches:delete" }
    methods:  DELETE
