csr_index:
    path:     /
    defaults: { _controller: "AppBundle:Csr:index" }
    methods:  GET

csr_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Csr:show" }
    methods:  GET

csr_new:
    path:     /new
    defaults: { _controller: "AppBundle:Csr:new" }
    methods:  [GET, POST]

csr_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Csr:edit" }
    methods:  [GET, POST]

csr_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Csr:delete" }
    methods:  DELETE
