download_index:
    path:     /
    defaults: { _controller: "AppBundle:Download:index" }
    methods:  GET

download_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Download:show" }
    methods:  GET

download_new:
    path:     /new
    defaults: { _controller: "AppBundle:Download:new" }
    methods:  [GET, POST]

download_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Download:edit" }
    methods:  [GET, POST]

download_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Download:delete" }
    methods:  DELETE
