history_index:
    path:     /history/
    defaults: { _controller: "AppBundle:History:index" }
    methods:  GET

history_show:
    path:     /history/{id}/show
    defaults: { _controller: "AppBundle:History:show" }
    methods:  GET

history_new:
    path:     /admin/history/new
    defaults: { _controller: "AppBundle:History:new" }
    methods:  [GET, POST]

history_edit:
    path:     /admin/history/{id}/edit
    defaults: { _controller: "AppBundle:History:edit" }
    methods:  [GET, POST]

history_delete:
    path:     /admin/history/{id}/delete
    defaults: { _controller: "AppBundle:History:delete" }
    methods:  DELETE
