history_index:
    path:     /
    defaults: { _controller: "AppBundle:History:index" }
    methods:  GET

history_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:History:show" }
    methods:  GET

history_new:
    path:     /new
    defaults: { _controller: "AppBundle:History:new" }
    methods:  [GET, POST]

history_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:History:edit" }
    methods:  [GET, POST]

history_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:History:delete" }
    methods:  DELETE
