messages_index:
    path:     /
    defaults: { _controller: "AppBundle:Messages:index" }
    methods:  GET

messages_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Messages:show" }
    methods:  GET

messages_new:
    path:     /new
    defaults: { _controller: "AppBundle:Messages:new" }
    methods:  [GET, POST]

messages_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Messages:edit" }
    methods:  [GET, POST]

messages_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Messages:delete" }
    methods:  DELETE
