messages_index:
    path:     /messages/
    defaults: { _controller: "AppBundle:Messages:index" }
    methods:  GET

messages_show:
    path:     /messages/{id}/show
    defaults: { _controller: "AppBundle:Messages:show" }
    methods:  GET

messages_new:
    path:     /admin/messages/new
    defaults: { _controller: "AppBundle:Messages:new" }
    methods:  [GET, POST]

messages_edit:
    path:     /admin/messages/{id}/edit
    defaults: { _controller: "AppBundle:Messages:edit" }
    methods:  [GET, POST]

messages_delete:
    path:     /admin/messages/{id}/delete
    defaults: { _controller: "AppBundle:Messages:delete" }
    methods:  DELETE
