mission_index:
    path:     /mission/
    defaults: { _controller: "AppBundle:Mission:index" }
    methods:  GET

mission_show:
    path:     /mission/{id}/show
    defaults: { _controller: "AppBundle:Mission:show" }
    methods:  GET

mission_new:
    path:     /admin/mission/new
    defaults: { _controller: "AppBundle:Mission:new" }
    methods:  [GET, POST]

mission_edit:
    path:     /admin/mission/{id}/edit
    defaults: { _controller: "AppBundle:Mission:edit" }
    methods:  [GET, POST]

mission_delete:
    path:     /admin/mission/{id}/delete
    defaults: { _controller: "AppBundle:Mission:delete" }
    methods:  DELETE
