peoples_index:
    path:     /
    defaults: { _controller: "AppBundle:Peoples:index" }
    methods:  GET

peoples_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Peoples:show" }
    methods:  GET

peoples_new:
    path:     /new
    defaults: { _controller: "AppBundle:Peoples:new" }
    methods:  [GET, POST]

peoples_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Peoples:edit" }
    methods:  [GET, POST]

peoples_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Peoples:delete" }
    methods:  DELETE
