vision_index:
    path:     /
    defaults: { _controller: "AppBundle:Vision:index" }
    methods:  GET

vision_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Vision:show" }
    methods:  GET

vision_new:
    path:     /new
    defaults: { _controller: "AppBundle:Vision:new" }
    methods:  [GET, POST]

vision_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Vision:edit" }
    methods:  [GET, POST]

vision_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Vision:delete" }
    methods:  DELETE
