vision_index:
    path:     /vision/
    defaults: { _controller: "AppBundle:Vision:index" }
    methods:  GET

vision_show:
    path:     /vision/{id}/show
    defaults: { _controller: "AppBundle:Vision:show" }
    methods:  GET

vision_new:
    path:     /admin/vision/new
    defaults: { _controller: "AppBundle:Vision:new" }
    methods:  [GET, POST]

vision_edit:
    path:     /admin/vision/{id}/edit
    defaults: { _controller: "AppBundle:Vision:edit" }
    methods:  [GET, POST]

vision_delete:
    path:     /admin/vision/{id}/delete
    defaults: { _controller: "AppBundle:Vision:delete" }
    methods:  DELETE
