whatwedo_index:
    path:     /whatwedo/
    defaults: { _controller: "AppBundle:Whatwedo:index" }
    methods:  GET

whatwedo_show:
    path:     /whatwedo/{id}/show
    defaults: { _controller: "AppBundle:Whatwedo:show" }
    methods:  GET

whatwedo_new:
    path:     /admin/whatwedo/new
    defaults: { _controller: "AppBundle:Whatwedo:new" }
    methods:  [GET, POST]

whatwedo_edit:
    path:     /admin/whatwedo/{id}/edit
    defaults: { _controller: "AppBundle:Whatwedo:edit" }
    methods:  [GET, POST]

whatwedo_delete:
    path:     /admin/whatwedo/{id}/delete
    defaults: { _controller: "AppBundle:Whatwedo:delete" }
    methods:  DELETE
