app_career:
    resource: "@AppBundle/Resources/config/routing/career.yml"
    prefix:   /
app_contactus:
    resource: "@AppBundle/Resources/config/routing/contactus.yml"
    prefix:   /
app_csr:
    resource: "@AppBundle/Resources/config/routing/csr.yml"
    prefix:   /
app_download:
    resource: "@AppBundle/Resources/config/routing/download.yml"
    prefix:   /
app_news:
    resource: "@AppBundle/Resources/config/routing/news.yml"
    prefix:   /
app_peoples:
    resource: "@AppBundle/Resources/config/routing/peoples.yml"
    prefix:   /
app_unites:
    resource: "@AppBundle/Resources/config/routing/unites.yml"
    prefix:   /
app_slide:
    resource: "@AppBundle/Resources/config/routing/slide.yml"
    prefix:   /
app_logo:
    resource: "@AppBundle/Resources/config/routing/logo.yml"
    prefix:   /
app_quote:
    resource: "@AppBundle/Resources/config/routing/quote.yml"
    prefix:   /
app_aboutus:
    resource: "@AppBundle/Resources/config/routing/aboutus.yml"
    prefix:   /
