app_branches:
    resource: "@AppBundle/Resources/config/routing/branches.yml"
    prefix:   /
app_career:
    resource: "@AppBundle/Resources/config/routing/career.yml"
    prefix:   /
app_contactus:
    resource: "@AppBundle/Resources/config/routing/contactus.yml"
    prefix:   /
app_csr:
    resource: "@AppBundle/Resources/config/routing/csr.yml"
    prefix:   /
app_download:
    resource: "@AppBundle/Resources/config/routing/download.yml"
    prefix:   /
app_history:
    resource: "@AppBundle/Resources/config/routing/history.yml"
    prefix:   /
app_messages:
    resource: "@AppBundle/Resources/config/routing/messages.yml"
    prefix:   /
app_mission:
    resource: "@AppBundle/Resources/config/routing/mission.yml"
    prefix:   /
app_news:
    resource: "@AppBundle/Resources/config/routing/news.yml"
    prefix:   /
app_overview:
    resource: "@AppBundle/Resources/config/routing/overview.yml"
    prefix:   /
app_peoples:
    resource: "@AppBundle/Resources/config/routing/peoples.yml"
    prefix:   /
app_unites:
    resource: "@AppBundle/Resources/config/routing/unites.yml"
    prefix:   /
app_vision:
    resource: "@AppBundle/Resources/config/routing/vision.yml"
    prefix:   /
app_whatwedo:
    resource: "@AppBundle/Resources/config/routing/whatwedo.yml"
    prefix:   /
app_whoweare:
    resource: "@AppBundle/Resources/config/routing/whoweare.yml"
    prefix:   /
