AppBundle\Entity\Branches:
 type: entity
 table: branches
 repositoryClass: AppBundle\Repository\BranchesRepository
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  brancheName:
   type: string
  address:
   type: text
  phone:
   type: string
  facisimile:
   type: string
