AppBundle\Entity\Peoples:
 type: entity
 table: peoples
 repositoryClass: AppBundle\Repository\PeoplesRepository
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  name:
   type: string
  description:
   type: string
  profileImage:
   type: string
