AppBundle\Entity\Unites:
 type: entity
 table: unites
 repositoryClass: AppBundle\Repository\UnitesRepository
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  title:
   type: string
  story:
   type: text
  largeImage:
   type: string
 oneToMany:
  unites_image:
   targetEntity: Buimage
   orphanRemoval: true
   mappedBy: unites
