AppBundle\Entity\Whoweare:
 type: entity
 table: whoweare
 repositoryClass: AppBundle\Repository\WhoweareRepository
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  title:
   type: string
  whoweare:
   type: text
  largeImage:
   type: string
